services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
     - ./data:/data:rw
    environment:
     - ADMIN_TOKEN=${ADMIN_TOKEN}
     - WEBSOCKET_ENABLED=true
     - SIGNUPS_ALLOWED=false
     - DOMAIN=${DOMAIN}
    networks:
      - default
      - netstackbridge

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: unless-stopped
    environment:
      RCLONE_REMOTE_NAME: 'RcloneBackup'
      RCLONE_REMOTE_DIR: ${RCLONE_REMOTE_DIR}
      CRON: '0 5 * * WED'
      ZIP_ENABLE: 'TRUE'
      ZIP_PASSWORD: ${RCLONE_BACKUP_ENCRYPTION_PASSWORD}
      ZIP_TYPE: '7z'
      BACKUP_FILE_SUFFIX: '%Y-%m-%d_%H-%M-%S'
      BACKUP_KEEP_DAYS: 30
      TIMEZONE: 'Europe/Vienna'
    volumes:
      - ~/.config/rclone:/config/rclone
      - ./data:/bitwarden/data:r

networks:
  default:
  netstackbridge:
    external: true
    name: netstack_bridge
